# Generated by Django 6.0.1 on 2026-01-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('kzt', 'KZT')], default='usd', max_length=3, verbose_name='валюта'),
        ),
    ]
