# Generated by Django 6.0.1 on 2026-01-08 17:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='дата и время редактирования')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('percent', models.PositiveIntegerField(help_text='скидка в процентах', validators=[django.core.validators.MaxValueValidator(100, 'скидка не может быть больше 100%!')], verbose_name='процент скидки')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
                'ordering': ('-percent',),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='дата и время редактирования')),
                ('name', models.CharField(max_length=255)),
                ('percent', models.PositiveIntegerField(help_text='налог в процентах', validators=[django.core.validators.MaxValueValidator(100, 'процент не может превышать значение 100!')], verbose_name='процент')),
            ],
            options={
                'verbose_name': 'налог',
                'verbose_name_plural': 'налоги',
                'ordering': ('-percent',),
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.discount', verbose_name='скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tax', verbose_name='налог'),
        ),
    ]
