# Generated by Django 6.0.1 on 2026-01-08 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discount_tax_alter_order_is_paid_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveIntegerField(help_text='скидка в процентах', validators=[django.core.validators.MaxValueValidator(100, 'скидка не может быть больше 100%')], verbose_name='процент скидки'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percent',
            field=models.PositiveIntegerField(help_text='налог в процентах', validators=[django.core.validators.MaxValueValidator(100, 'процент не может превышать значение 100')], verbose_name='процент'),
        ),
    ]
