# Generated by Django 6.0.1 on 2026-01-08 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_discount_percent_alter_tax_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveIntegerField(help_text='скидка в процентах', validators=[django.core.validators.MaxValueValidator(100, 'скидка не может быть больше 100')], verbose_name='процент скидки'),
        ),
    ]
