# Generated by Django 6.0.1 on 2026-01-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='промокод'),
        ),
    ]
